GET http://localhost:8080/api/employee/all

###

GET http://localhost:8080/api/employee/1

###

POST http://localhost:8080/api/employee
Content-Type: application/json

{
    "firstName": "Andrzej",
    "lastName": "Kowalczyk",
    "email": "kowal@gmail.com",
    "salary": "3200"
}

###

PUT http://localhost:8080/api/employee
Content-Type: application/json

{
    "id": "2",
    "firstName": "Jan",
    "lastName": "Kowalski",
    "email": "jan.kowalski@gmail.com",
    "salary": "3500"
}

###

DELETE  http://localhost:8080/api/employee/2